name: Versioning, Build & Release

on:
  push:
    branches: [main]

jobs:
  versioning:
    name: Versioning
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install Dependencies
        run: npm ci

      - name: Type Check
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Run TS script
        id: ts_versioning
        run: |
          npx tsc .github/workflows/release.ts --outDir dist/ --module NodeNext --moduleResolution nodenext
          node dist/release.js

    outputs:
      version: ${{ steps.ts_versioning.outputs.version }}

  electron-release:
    name: Build & Release Electron App
    permissions:
      contents: write
    needs: versioning
    if: ${{ needs.versioning.outputs.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.versioning.outputs.version }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install Dependencies
        run: npm install # must reinstall for different OS

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.versioning.outputs.version }}
          generate_release_notes: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz

  web-build:
    name: Build & Deploy Web App
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: versioning
    if: ${{ needs.versioning.outputs.version }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.versioning.outputs.version }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install Dependencies
        run: npm install

      - name: build-web
        run: npm run build:web

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./out/renderer"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
